name: Strojenie i walidacja regulatorów

on:
  workflow_dispatch:
    inputs:
      regulator:
        description: 'Wybierz regulator do przetestowania'
        required: true
        default: 'regulator_pid'
        type: choice
        options:
          - regulator_pid
          - regulator_pi
          - regulator_dwupolozeniowy

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t regulator-sim:test -f kontener/Dockerfile .

      - name: Run full pipeline
        run: |
          docker run --rm \
            -e REGULATOR=${{ github.event.inputs.regulator }} \
            -v ${{ github.workspace }}/wyniki:/app/wyniki \
            regulator-sim:test python src/uruchom_pipeline.py

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: raporty_${{ github.event.inputs.regulator }}
          path: wyniki/
