name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/pid-sim:${{ github.sha }}
          IMAGE=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> image.env
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Save IMAGE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-env
          path: image.env

  validate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Load IMAGE from artifact
        uses: actions/download-artifact@v4
        with:
          name: image-env

      - run: cat image.env >> $GITHUB_ENV

      - name: Run validation inside container
        run: |
          mkdir -p out
          docker run --rm -e OUT_DIR=/out -v ${{ github.workspace }}/out:/out $IMAGE

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: out
